namespace CannedNet;

public enum ObjectiveType
{
    Default = -1,
    [Obsolete]
    FirstSessionOfDay = 1,
    AddAFriend,
    PartyUp,
    AllOtherChallenges,
    [Obsolete]
    LevelUp,
    CheerAPlayer,
    PointedAtPlayer,
    CheerARoom,
    SubscribeToPlayer,
    DailyObjective1,
    DailyObjective2,
    DailyObjective3,
    AllDailyObjectives,
    CompleteAnyDaily,
    CompleteAnyWeekly,
    [Obsolete]
    OOBE_GoToLockerRoom = 20,
    [Obsolete]
    OOBE_GoToActivity,
    [Obsolete]
    OOBE_FinishActivity,
    NUX_PunchcardObjective = 25,
    NUX_AllPunchcardObjectives,
    GoToRecCenter = 30,
    FinishActivity,
    VisitACustomRoom,
    CreateACustomRoom,
    ScoreBasketInRecCenter = 35,
    UploadPhotoToRecNet,
    UpdatePlayerBio,
    SaveOutfitSlot,
    PurchaseClothingItem,
    PurchaseNonClothingItem,
    DrinkWater,
    ColorOnWhiteboard,
    SetBasketballSkin,
    ThrowBasketball,
    PlaceInventionInDorm,
    ChangeDormRoomSkin,
    ToggleOwnedClothes,
    EquipHat,
    LoadOutfit,
    SaveNewOutfitSlot,
    SpawnCamera,
    TakeSelfie,
    PrintSelfie,
    TakePictureOfPlayer,
    PrintPictureOfPlayer,
    PublishSelfieWithPlayer,
    SpawnFoodWithOtherPlayers,
    EmoteInRecCenter,
    SendRoomChatInRecCenter,
    UseFrendotron,
    GoToDormRoom,
    VisitSpecificRoom,
    VisitPublicRRO,
    VisitPublicRoomBySource,
    FavoriteARoom,
    TakePhotoWithFilter,
    OpenYourPlayerProfile,
    OpenOnlineStatusModal,
    ChangeProfilePicture,
    ChangePlayerDisplayName,
    ChangePlayerDescriptionText,
    OpenPlayerPronounsModal,
    OpenOtherPlayersProfile,
    VisitPlayersPortfolio,
    FavoriteAFriend,
    CharadesGames = 100,
    CharadesWinsPerformer,
    CharadesWinsGuesser,
    DiscGolfWins = 200,
    DiscGolfGames,
    DiscGolfHolesUnderPar,
    DodgeballWins = 300,
    DodgeballGames,
    DodgeballHits,
    PaddleballGames = 400,
    PaddleballWins,
    PaddleballScores,
    PaintballAnyModeGames = 500,
    PaintballAnyModeWins,
    PaintballAnyModeHits,
    PaintballCTFWins = 600,
    PaintballCTFGames,
    PaintballCTFHits,
    PaintballFlagCaptures,
    PaintballTeamBattleWins = 700,
    PaintballTeamBattleGames,
    PaintballTeamBattleHits,
    PaintballFreeForAllWins = 710,
    PaintballFreeForAllGames,
    PaintballFreeForAllHits,
    SoccerWins = 800,
    SoccerGames,
    SoccerGoals,
    BowlingGames = 900,
    BowlingWins,
    BowlingStrike,
    QuestGames = 1000,
    QuestWins,
    QuestPlayerRevives,
    QuestEnemyKills,
    QuestGames_Goblin1 = 1010,
    QuestWins_Goblin1,
    QuestPlayerRevives_Goblin1,
    QuestEnemyKills_Goblin1,
    QuestGames_Goblin2 = 1020,
    QuestWins_Goblin2,
    QuestPlayerRevives_Goblin2,
    QuestEnemyKills_Goblin2,
    QuestGames_Scifi1 = 1030,
    QuestWins_Scifi1,
    QuestPlayerRevives_Scifi1,
    QuestEnemyKills_Scifi1,
    QuestGames_Pirate1 = 1040,
    QuestWins_Pirate1,
    QuestPlayerRevives_Pirate1,
    QuestEnemyKills_Pirate1,
    QuestGames_Dracula1 = 1050,
    QuestWins_Dracula1,
    QuestPlayerRevives_Dracula1,
    QuestEnemyKills_Dracula1,
    ArenaGames = 2000,
    ArenaWins,
    ArenaPlayerRevives,
    ArenaHeroTags,
    ArenaBotTags,
    RecRoyaleGames = 3000,
    RecRoyaleWins,
    RecRoyaleTags,
    StuntRunnerGames = 4000,
    StuntRunnerWins,
    RecRallyGames = 5000,
    RecRallyWins
}
