// <auto-generated />
using System;
using System.Collections.Generic;
using CannedNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CannedNet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614165446_MakeDataSavedAtNullable")]
    partial class MakeDataSavedAtNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CannedNet.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("accountId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("createdAt");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("displayName");

                    b.Property<int?>("IdentityFlags")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("identityFlags");

                    b.Property<bool>("IsJunior")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("isJunior");

                    b.Property<int?>("PersonalPronouns")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("personalPronouns");

                    b.Property<int?>("Platforms")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("platforms");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text")
                        .HasJsonPropertyName("profileImage");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("username");

                    b.HasKey("AccountId");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("CannedNet.AvatarItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarItemDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("avatarItemDesc");

                    b.Property<int>("AvatarItemType")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("avatarItemType");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("friendlyName");

                    b.Property<int>("OwnerAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("PlatformMask")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("platformMask");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("rarity");

                    b.Property<string>("Tooltip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("tooltip");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId");

                    b.ToTable("avatar_items", (string)null);
                });

            modelBuilder.Entity("CannedNet.CachedLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("accountId");

                    b.Property<DateTime>("LastLoginTime")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("lastLoginTime");

                    b.Property<int>("Platform")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("platform");

                    b.Property<string>("PlatformID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("platformId");

                    b.Property<bool>("RequirePassword")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("requirePassword");

                    b.HasKey("Id");

                    b.HasIndex("Platform", "PlatformID");

                    b.ToTable("cached_logins", (string)null);
                });

            modelBuilder.Entity("CannedNet.LoadScreen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("imageUrl");

                    b.Property<bool>("IsThumbnail")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("isThumbnail");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Tooltip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("tooltip");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("load_screens", (string)null);
                });

            modelBuilder.Entity("CannedNet.Models.ConsumableItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveDurationMinutes")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("ActiveDurationMinutes");

                    b.Property<string>("ConsumableItemDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("ConsumableItemDesc");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("Count");

                    b.PrimitiveCollection<List<DateTime>>("CreatedAts")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone[]")
                        .HasJsonPropertyName("CreatedAts");

                    b.PrimitiveCollection<List<int>>("Ids")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasJsonPropertyName("Ids");

                    b.Property<int>("InitialCount")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("InitialCount");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("IsActive");

                    b.Property<bool>("IsTransferable")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("IsTransferable");

                    b.Property<int>("OwnerAccountId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId");

                    b.ToTable("consumable_items", (string)null);
                });

            modelBuilder.Entity("CannedNet.Models.EarnableReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarItemDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("avatarItemDesc");

                    b.Property<int>("AvatarItemType")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("avatarItemType");

                    b.Property<string>("ConsumableItemDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("consumableItemDesc");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("friendlyName");

                    b.Property<int>("GiftRarity")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("giftRarity");

                    b.Property<int>("RewardContext")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("rewardContext");

                    b.HasKey("Id");

                    b.HasIndex("RewardContext");

                    b.ToTable("earnable_rewards", (string)null);
                });

            modelBuilder.Entity("CannedNet.Models.GiftDrop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarItemDesc")
                        .HasColumnType("text");

                    b.Property<int>("AvatarItemType")
                        .HasColumnType("integer");

                    b.Property<string>("ConsumableItemDesc")
                        .HasColumnType("text");

                    b.Property<int>("Context")
                        .HasColumnType("integer");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<int>("CurrencyType")
                        .HasColumnType("integer");

                    b.Property<string>("EquipmentModificationGuid")
                        .HasColumnType("text");

                    b.Property<string>("EquipmentPrefabName")
                        .HasColumnType("text");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GiftDropId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsQuery")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemSetFriendlyName")
                        .HasColumnType("text");

                    b.Property<int?>("ItemSetId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<int>("StorefrontItemId")
                        .HasColumnType("integer");

                    b.Property<bool>("SubscribersOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("Tooltip")
                        .HasColumnType("text");

                    b.Property<bool>("Unique")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("StorefrontItemId");

                    b.ToTable("gift_drops", (string)null);
                });

            modelBuilder.Entity("CannedNet.Models.ReceivedGift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarItemDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("avatarItemDesc");

                    b.Property<int>("AvatarItemType")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("avatarItemType");

                    b.Property<int>("BalanceType")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("balanceType");

                    b.Property<string>("ConsumableItemDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("consumableItemDesc");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("consumedAt");

                    b.Property<int>("Currency")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("currency");

                    b.Property<int>("CurrencyType")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("currencyType");

                    b.Property<string>("EquipmentModificationGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("equipmentModificationGuid");

                    b.Property<string>("EquipmentPrefabName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("equipmentPrefabName");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("friendlyName");

                    b.Property<int?>("FromPlayerId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("fromPlayerId");

                    b.Property<int>("GiftContext")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("giftContext");

                    b.Property<int>("GiftRarity")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("giftRarity");

                    b.Property<bool>("IsConsumed")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("isConsumed");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("message");

                    b.Property<int>("Platform")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("platform");

                    b.Property<int>("PlatformsToSpawnOn")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("platformsToSpawnOn");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("receivedAt");

                    b.Property<int>("ReceiverAccountId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("receiverAccountId");

                    b.Property<int>("Xp")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("xp");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverAccountId");

                    b.HasIndex("ReceiverAccountId", "IsConsumed");

                    b.ToTable("received_gifts", (string)null);
                });

            modelBuilder.Entity("CannedNet.Models.Storefront", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NextUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StorefrontType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("storefronts", (string)null);
                });

            modelBuilder.Entity("CannedNet.Models.StorefrontItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NewUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PurchasableItemId")
                        .HasColumnType("integer");

                    b.Property<int>("StorefrontId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StorefrontId");

                    b.ToTable("storefront_items", (string)null);
                });

            modelBuilder.Entity("CannedNet.Models.StorefrontPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrencyType")
                        .HasColumnType("integer");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("StorefrontItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StorefrontItemId");

                    b.ToTable("storefront_prices", (string)null);
                });

            modelBuilder.Entity("CannedNet.PlayerAvatar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FaceFeatures")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("FaceFeatures");

                    b.Property<string>("HairColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("HairColor");

                    b.Property<string>("OutfitSelections")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("OutfitSelections");

                    b.Property<int>("OwnerAccountId")
                        .HasColumnType("integer");

                    b.Property<string>("SkinColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("SkinColor");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId")
                        .IsUnique();

                    b.ToTable("player_avatars", (string)null);
                });

            modelBuilder.Entity("CannedNet.PlayerBio", b =>
                {
                    b.Property<int>("accountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasJsonPropertyName("accountId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("accountId"));

                    b.HasKey("accountId");

                    b.ToTable("player_bios", (string)null);
                });

            modelBuilder.Entity("CannedNet.PlayerProgression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("level");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("playerId");

                    b.Property<int>("Xp")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("xp");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("player_progressions", (string)null);
                });

            modelBuilder.Entity("CannedNet.PlayerSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("key");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("playerId");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("value");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Key")
                        .IsUnique();

                    b.ToTable("player_settings", (string)null);
                });

            modelBuilder.Entity("CannedNet.PromoExternalContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Tooltip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("tooltip");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("url");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("promo_external_contents", (string)null);
                });

            modelBuilder.Entity("CannedNet.PromoImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("imageUrl");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("sortOrder");

                    b.Property<string>("Tooltip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("tooltip");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("promo_images", (string)null);
                });

            modelBuilder.Entity("CannedNet.Room", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("Accessibility")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("accessibility");

                    b.Property<bool>("CloningAllowed")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("cloningAllowed");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("createdAt");

                    b.Property<int>("CreatorAccountId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("creatorAccountId");

                    b.Property<string>("CustomWarning")
                        .HasColumnType("text")
                        .HasJsonPropertyName("customWarning");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("description");

                    b.Property<bool>("DisableMicAutoMute")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("disableMicAutoMute");

                    b.Property<bool>("DisableRoomComments")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("disableRoomComments");

                    b.Property<bool>("EncryptVoiceChat")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("encryptVoiceChat");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("imageName");

                    b.Property<bool>("IsDorm")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("isDorm");

                    b.Property<bool>("IsRRO")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("isRRO");

                    b.Property<int>("MinLevel")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("minLevel");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("name");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("roomId");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("state");

                    b.Property<bool>("SupportsJuniors")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("supportsJuniors");

                    b.Property<bool>("SupportsLevelVoting")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("supportsLevelVoting");

                    b.Property<bool>("SupportsMobile")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("supportsMobile");

                    b.Property<bool>("SupportsQuest2")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("supportsQuest2");

                    b.Property<bool>("SupportsScreens")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("supportsScreens");

                    b.Property<bool>("SupportsTeleportVR")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("supportsTeleportVR");

                    b.Property<bool>("SupportsVRLow")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("supportsVRLow");

                    b.Property<bool>("SupportsWalkVR")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("supportsWalkVR");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("tags");

                    b.Property<int>("WarningMask")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("warningMask");

                    b.HasKey("Id");

                    b.HasIndex("CreatorAccountId");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("CannedNet.RoomInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EncryptVoiceChat")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("EncryptVoiceChat");

                    b.Property<int>("OwnerAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("clubId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("clubId");

                    b.Property<string>("dataBlob")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("dataBlob");

                    b.Property<int>("eventId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("eventId");

                    b.Property<bool>("isFull")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("isFull");

                    b.Property<bool>("isInProgress")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("isInProgress");

                    b.Property<bool>("isPrivate")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("isPrivate");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("location");

                    b.Property<int>("maxCapacity")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("maxCapacity");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("name");

                    b.Property<string>("photonRegionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("photonRegionId");

                    b.Property<string>("photonRoomId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("photonRoomId");

                    b.Property<string>("roomCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("roomCode");

                    b.Property<int>("roomId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("roomId");

                    b.Property<int>("roomInstanceId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("roomInstanceId");

                    b.Property<int>("roomInstanceType")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("roomInstanceType");

                    b.Property<int>("subRoomId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("subRoomId");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId", "roomId");

                    b.ToTable("room_instances", (string)null);
                });

            modelBuilder.Entity("CannedNet.RoomRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("accountId");

                    b.Property<int>("InvitedRole")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("invitedRole");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("role");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("room_roles", (string)null);
                });

            modelBuilder.Entity("CannedNet.SavedOutfit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FaceFeatures")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("FaceFeatures");

                    b.Property<string>("HairColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("HairColor");

                    b.Property<string>("OutfitSelections")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("OutfitSelections");

                    b.Property<int>("OwnerAccountId")
                        .HasColumnType("integer");

                    b.Property<string>("PreviewImageName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("PreviewImageName");

                    b.Property<string>("SkinColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("SkinColor");

                    b.Property<int>("Slot")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("Slot");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId")
                        .IsUnique();

                    b.ToTable("saved_outfits", (string)null);
                });

            modelBuilder.Entity("CannedNet.SubRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Accessibility")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("accessibility");

                    b.Property<string>("DataBlob")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("dataBlob");

                    b.Property<DateTime?>("DataSavedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("dataSavedAt");

                    b.Property<bool>("IsSandbox")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("isSandbox");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("maxPlayers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("name");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("SubRoomId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("subRoomId");

                    b.Property<string>("UnitySceneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("unitySceneId");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("sub_rooms", (string)null);
                });

            modelBuilder.Entity("CannedNet.TokenBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Balance")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("Balance");

                    b.Property<int>("BalanceType")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("BalanceType");

                    b.Property<int>("CurrencyType")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("CurrencyType");

                    b.Property<int>("Platform")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("Platform");

                    b.HasKey("Id");

                    b.ToTable("token_balances", (string)null);
                });

            modelBuilder.Entity("CannedNet.Models.GiftDrop", b =>
                {
                    b.HasOne("CannedNet.Models.StorefrontItem", "StorefrontItem")
                        .WithMany("GiftDrops")
                        .HasForeignKey("StorefrontItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StorefrontItem");
                });

            modelBuilder.Entity("CannedNet.Models.StorefrontItem", b =>
                {
                    b.HasOne("CannedNet.Models.Storefront", "Storefront")
                        .WithMany("Items")
                        .HasForeignKey("StorefrontId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Storefront");
                });

            modelBuilder.Entity("CannedNet.Models.StorefrontPrice", b =>
                {
                    b.HasOne("CannedNet.Models.StorefrontItem", "StorefrontItem")
                        .WithMany("Prices")
                        .HasForeignKey("StorefrontItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StorefrontItem");
                });

            modelBuilder.Entity("CannedNet.Models.Storefront", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CannedNet.Models.StorefrontItem", b =>
                {
                    b.Navigation("GiftDrops");

                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
